# Generated by Django 2.2.6 on 2019-11-23 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='подписчики')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('short_text', models.TextField(blank=True, verbose_name='короткое описание')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='картинка')),
                ('x', models.FloatField(verbose_name='долгота')),
                ('y', models.FloatField(verbose_name='широта')),
                ('tags', models.ManyToManyField(related_name='places', to='places.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
    ]
