# Generated by Django 2.2.6 on 2019-11-23 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visitors',
            field=models.ManyToManyField(related_name='visited_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
