# Generated by Django 2.2.6 on 2019-11-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('points', models.FloatField(default=0, verbose_name='очки')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
            },
        ),
    ]
