# Generated by Django 2.2.6 on 2019-11-23 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='users',
            field=models.ManyToManyField(related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='пользователи, получившие ачивку'),
        ),
    ]
